language: ruby
sudo: false
rvm:
  - 2.1
  - 2.0
gemfile:
  - gemfiles/rails4_0.gemfile
  - gemfiles/rails4_1.gemfile
  - gemfiles/rails4_2.gemfile
before_script:
  - RAILS_ENV=test bundle exec rake db:create db:migrate
script:
  - bundle exec rake spec
notifications:
  email: false
